spring:
#  h2:
#    console:
#      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: root
    password: 102030
    initialization-mode: always
    sql-script-encoding: utf-8

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true # ??? ?? ??
    hibernate:
      ddl-auto: create

server:
  port: 8070


logging:
  level:
    org:
      springframework.transaction.interceptor : TRACE
      springframework.transaction : TRACE

#logging:
#  level:
#    root: error
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
